# This will be the first part of the title tag for your site <title> site.name + page.title </title>
name: IBM Community Radio

# Populates the meta description for the site. Should be under 150 characters for best SEO purposes.
description: "Website for IBM Community Radio"

# Owner (organization or individual) of site content
author: IBM Community Radio

#url: "[http:// ]"
url: "https://ibm.biz/ibm-radio"

markdown: kramdown

# Pagination variable for how many posts to show in a list
paginate: 5

# Style of permalinks
permalink: /:categories/:title

gems: ['jekyll-sitemap']

# pygments: true

exclude: [node_modules, Gruntfile.js, package.json]
